### ISSUE TITLE
Lightning address not working

### ISSUE THREAD

**Issue by fiksn** [bumi/lnme#15]
I have LnMe installed and configured with remote LND 0.13.1-beta. The payment via page works fine, however when trying out Lightning Address with Zebedee I get following error:

![zebedee](https://user-images.githubusercontent.com/1640719/134824280-149bee5c-f764-44da-a895-f0cbacf8fb25.jpg)

**Comment by bumi** [comment]
thanks for the report! I haven't tried Zebedee, yet. 
just to confirm you also can not send to sats@ln.michaelbumann.com ? what's your lightning address, that I can test it?

**Comment by fiksn** [comment]
I can confirm this is fixed with 1.2.0.
