### ISSUE TITLE
Setting up Lightning Addresses in lnme

### ISSUE THREAD

**Issue by trbouma** [bumi/lnme#27]
Do you have any further instructions on how to setup Lightning addresses? I see that you support it, but I don't see any instructions.

I am very keen to get this going!

Thanks!

Tim

**Comment by bumi** [comment]
no need to set anything up. LnMe has catch-all support, so basically you can use any address {anything}@{YOUR domain}. 

so after your deployment to heroku now you have already for example `trbouma@lnme-yow3.herokuapp.com` (I just sent 10sats to that one) - you now only need to configure a domain on heroku.

**Comment by trbouma** [comment]
Wow! Thank you! It came through. Now I need to figure out how to pay to a lightning address from my bluewallet. I can't seem to do it.

**Comment by bumi** [comment]
use use it in the send screen (instead of an invoice)

**Comment by trbouma** [comment]
Got it! I just registered lnpay.ca so pretty excited when this is updated to use. Another question, I notice that sometimes I experience latency that results in a timeout. Do I need to upgrade the Heroku dyno so it doesn't go to sleep (if this is the problem)?

**Comment by bumi** [comment]
Heroku has a 30 seconds request timeout. So any request must be processed within that time. 
I am not sure how much latency the Tor connection adds (maybe @crc32 has an idea?). But I think it is fine. 
You should update your dyno that it does not go to sleep - booting up the dyno with Tor is slow.

**Comment by crc32** [comment]
I've not seen any issues on my side with Heroku timing out after adding Tor (and I'm using the free tier). If you watch the live logs while you ping the system, it can sync with Tor, connect to your node, and retrieve the needed data within about 10 seconds. Also I've let it sit there for awhile while it's waiting for confirmation (on the website component) and it still seems to work just fine.

I DO see issues with Breez wallet timing out when paying invoices, but I think that's a Breez-to-my node issue. Other tested routes have worked just fine.
