### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by AaronDewes** [bumi/lnme#28]
Having a logo for this project would be great for adding it in app stores like Citadel's or Umbrel's.

**Comment by jerolimov** [comment]
Hi @AaronDewes, hi @bumi,

that's a great idea. I sketched quickly something. 🤣 

Feel free to use it, reassemble it, or ping me if you have other ideas. And don't worry. I'm not a designer, so I'm not offended if you take something completely different. 😄 

![lnme](https://user-images.githubusercontent.com/139310/140197811-d87b4cf8-388b-430b-95de-4a59e3a16305.png)

The attached zip contains a sketch and svg file.
[lnme-icon.zip](https://github.com/bumi/lnme/files/7470858/lnme-icon.zip)

**Comment by bumi** [comment]
nice! looks fun. 
@AaronDewes you choose one!

**Comment by jerolimov** [comment]
Here are some more lightning ideas:

![lnme](https://user-images.githubusercontent.com/139310/140310897-8e881686-fd2a-4f04-92ca-ca7537fb5fe6.png)

[lnme-icon.zip](https://github.com/bumi/lnme/files/7474650/lnme-icon.zip)

**Comment by bumi** [comment]
I still like the blue/green background with the yellow ⚡️ best.
@AaronDewes what do you say, can we use that for the store?

**Comment by AaronDewes** [comment]
Sounds great! Which one exactly?

**Comment by bumi** [comment]
do you have a favorit?

**Comment by AaronDewes** [comment]
![IMG_20211111_204326_731](https://user-images.githubusercontent.com/67546953/141359082-f94b3a0c-5eef-45fa-9743-ec20e5cf54a3.jpg)

I prefer this one. How about you?

**Comment by bumi** [comment]
bäm, let's use that one! //cc @jerolimov

**Comment by trbouma** [comment]
I really like the one in the red circle too. Another consideration is that it transposes well to black-and-white; I have severe colour-blindness and prefer simple bold icons. That one can be easily made into a very-simple b&w logo. I like the colours too, but my earlier point should indicate to not ask my opinion of colours.

**Comment by bumi** [comment]
@jerolimov can you put that one as a file (in as many formats as possible? png? svg?) into the repo and make a PR? 
can't believe that LnMe now has a logo! \o/

**Comment by jerolimov** [comment]
Yep, on my to do list. :)
