### ISSUE TITLE
LNURL wrong callback

### ISSUE THREAD

**Issue by Heisenberg-CZE** [bumi/lnme#36]
Hi,
I installed LnMe on my node (version 1.5.0) with default configuration. Basic webpage (or custom) works fine, my LND is able to receive sats. However when I tried LNURL, the callback host is not hostname of my node but the IP of the client. I tried that from few places/devices and everywhere it's the same.

You can check it right now on - [https://donate.platbybudoucnosti.cz/lnurlp/test](https://donate.platbybudoucnosti.cz/lnurlp/test)

You will see, that the callback URL is pointing to your IP address instead of my hostname.

What am I doing wrong?

Thank you

**Comment by crc32** [comment]
I'm not sure, but there was an update in October or November which doesn't seem to respect the proxy. I updated in May, but had to roll it back to an earlier bit.

**Comment by Heisenberg-CZE** [comment]
Thank you for the info. I was forced to manually revert the changes, that were made in [https://github.com/bumi/lnme/pull/30](https://github.com/bumi/lnme/pull/30) and compile it from source.

Right now it is working as a workaround.

**Comment by bumi** [comment]
Hey, thanks for reporting! 
Can you tell me about your setup? Do you use a proxy? 
I will immediately fix this. sorry for the problem.

**Comment by bumi** [comment]
Seems I completely failed there. 😱 
Can you check the latest master if that works for you?

**Comment by Heisenberg-CZE** [comment]
I don't use proxy at all. My setup is very simple - node with public IP and domain name pointing to that IP.

However I tried latest master and it's working fine! The LNURL JSON looks good (correct hostname instead of client IP) and also I tried to pay - it works :)

Thank you very much for such quick patch and also for you work!

**Comment by bumi** [comment]
@AaronDewes I messed something up here. Just to make sure your setup is using the correct HTTP proxy headers: `X-Forwarded-Host` and `X-Forwarded-Proto`.

In a future iteration I should also support the `Forwarded` header (but seems the echo framework currently does not provide parsing for that)

**Comment by bumi** [comment]
@Heisenberg-CZE @crc32 let me know if I can still help anything.
(also seems [https://donate.platbybudoucnosti.cz](https://donate.platbybudoucnosti.cz/lnurlp/test) is currently not reachable for me?)

**Comment by Heisenberg-CZE** [comment]
Yes, it is not reachable for now - it's planned :) Thanks for patch.
